const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS__REQUEST';
const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS__SUCCESS';
const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILED';
const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
const SET_MULTI_FILTER = 'SET_MULTI_FILTER';

export {
  FETCH_PROJECTS_REQUEST,
  FETCH_PROJECTS_SUCCESS,
  FETCH_PROJECTS_FAILURE,
  SET_SEARCH_FILTER,
  SET_MULTI_FILTER,
};
